CREATE TABLE users (
	id 			BIGSERIAL PRIMARY KEY NOT NULL,
	username	TEXT NOT NULL UNIQUE,
	nickname	TEXT,
	password	TEXT
);

CREATE TABLE servers (
	id			BIGSERIAL PRIMARY KEY NOT NULL,
	nickname	TEXT,
	owner		BIGINT NOT NULL REFERENCES users(id)
);

CREATE TABLE channels (
	id			BIGSERIAL PRIMARY KEY NOT NULL,
	server		BIGINT NOT NULL REFERENCES servers(id) ON DELETE CASCADE,
	name		TEXT
);

CREATE TABLE attachments (
	id			BIGSERIAL PRIMARY KEY NOT NULL,
	name		TEXT,
	owner		BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	server		BIGINT NOT NULL REFERENCES servers(id) ON DELETE CASCADE,
	content		bytea
);

CREATE TABLE messages (
	id			BIGSERIAL PRIMARY KEY NOT NULL,
	sender		BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	server		BIGINT NOT NULL,
	channel		BIGINT NOT NULL,
	reply		BIGINT, 
	text		TEXT,
	timestamp	BIGINT
);

CREATE TABLE reactions (
	id			BIGSERIAL PRIMARY KEY NOT NULL,
	messageid	BIGINT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
	userid		BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	emoji		INTEGER NOT NULL
);

CREATE TABLE server_members (
	id			BIGSERIAL PRIMARY KEY NOT NULL,
	server_id	BIGINT NOT NULL,
	userid		BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	nickname	TEXT
);

CREATE TABLE channel_events (
	id				BIGSERIAL PRIMARY KEY NOT NULL,
	channel_id		BIGINT NOT NULL,
	server_id		BIGINT NOT NULL,
	timestamp		BIGINT NOT NULL,
	event_type		INTEGER NOT NULL,
	message			BIGINT REFERENCES messages(id) ON DELETE CASCADE,
	reaction		BIGINT REFERENCES reactions(id) ON DELETE CASCADE,
	creator			BIGINT REFERENCES users(id) ON DELETE CASCADE,
	deleted			BIGINT
);

CREATE TABLE server_events (
	id				BIGSERIAL PRIMARY KEY NOT NULL,
	server_id		BIGINT NOT NULL,
	timestamp		BIGINT NOT NULL,
	event_type		INTEGER NOT NULL,
	creator			BIGINT REFERENCES users(id) ON DELETE CASCADE,
	deleted			BIGINT
);