[default.databases.sqlx]
url = "postgres://ivy:password@localhost/gaterdile_dev"
timeout = 10

[release.databases.sqlx]
url = "postgres://username:password@localhost/gaterdile"

# [development]
# address = "localhost"
# port = 9090