-- Add migration script here
CREATE TABLE users (
	id 			BIGSERIAL PRIMARY KEY NOT NULL UNIQUE,
	username	TEXT NOT NULL UNIQUE,
	nickname	TEXT,
	password	TEXT NOT NULL
);

CREATE TABLE communities (
	id			BIGSERIAL NOT NULL PRIMARY KEY UNIQUE,
	nickname	TEXT NOT NULL,
	owner		BIGINT REFERENCES users(id) ON DELETE SET NULL,
	is_public	BOOLEAN NOT NULL
);

CREATE TABLE rooms (
	id			BIGSERIAL PRIMARY KEY NOT NULL UNIQUE,
	server		BIGINT NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
	name		TEXT NOT NULL
);

CREATE TABLE roles (
	id			BIGSERIAL PRIMARY KEY NOT NULL UNIQUE,
	community	BIGINT NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
	name		TEXT NOT NULL,
	is_admin	BOOLEAN NOT NULL
);

CREATE TABLE room_visibility (
	roomid	BIGINT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
	roleid	BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
	PRIMARY KEY(roomid, roleid)
);

CREATE TABLE role_members (
	userid	BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	roleid	BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
	PRIMARY KEY(userid, roleid)
);

CREATE TABLE attachments (
	id			BIGSERIAL PRIMARY KEY NOT NULL UNIQUE,
	name		TEXT,
	owner		BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	server		BIGINT NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
	content		bytea
);

CREATE TABLE messages (
	id			BIGSERIAL PRIMARY KEY NOT NULL UNIQUE,
	sender		BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	server		BIGINT NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
	channel		BIGINT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
	reply		BIGINT REFERENCES messages(id) ON DELETE SET NULL,
	is_reply 	BOOLEAN NOT NULL,
	text		TEXT NOT NULL,
	timestamp	BIGINT NOT NULL
);

CREATE TABLE reactions (
	id			BIGSERIAL PRIMARY KEY NOT NULL UNIQUE,
	messageid	BIGINT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
	userid		BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	emoji		INTEGER NOT NULL
);

CREATE TABLE community_members (
	server_id	BIGINT NOT NULL REFERENCES communities(id)  ON DELETE CASCADE,
	userid		BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	nickname	TEXT,
	PRIMARY KEY(server_id, userid)
);

CREATE TABLE room_events (
	id				BIGSERIAL PRIMARY KEY NOT NULL UNIQUE,
	channel_id		BIGINT NOT NULL REFERENCES rooms(id)  ON DELETE CASCADE,
	server_id		BIGINT NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
	timestamp		BIGINT NOT NULL,
	event_type		INTEGER NOT NULL,
	message			BIGINT REFERENCES messages(id) ON DELETE CASCADE,
	reaction		BIGINT REFERENCES reactions(id) ON DELETE CASCADE,
	creator			BIGINT REFERENCES users(id) ON DELETE CASCADE,
	deleted			BIGINT
);

CREATE TABLE community_events (
	id				BIGSERIAL PRIMARY KEY NOT NULL UNIQUE,
	server_id		BIGINT NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
	timestamp		BIGINT NOT NULL,
	event_type		INTEGER NOT NULL,
	creator			BIGINT REFERENCES users(id) ON DELETE CASCADE,
	channel			BIGINT REFERENCES rooms(id) ON DELETE CASCADE,
	deleted			BIGINT
);

CREATE TABLE user_events (
	id				BIGSERIAL PRIMARY KEY NOT NULL UNIQUE,
	user_id			BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	timestamp		BIGINT NOT NULL,
	event_type		INTEGER NOT NULL,
	community		BIGINT REFERENCES communities(id) ON DELETE CASCADE,
	deleted			BIGINT
);

CREATE TABLE auth_tokens (
	id				BIGSERIAL PRIMARY KEY NOT NULL UNIQUE,
	expiry			BIGINT NOT NULL,
	token			TEXT NOT NULL,
	user_id			BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);
